config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # Root of the site
  root 'static_pages#home'

  get 'home'    => 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login'       => 'sessions#new'
  post 'login'      => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'

  resources :micro_posts
  resources :users


end

app/models/micro_post.rb
class MicroPost < ActiveRecord::Base

  belongs_to :user

  validates :content, length: { maximum: 140 }

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :remember_token

  has_many :micro_posts

  before_save { self.email.downcase! }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 255 }, format: VALID_EMAIL_REGEX

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/micro_posts_controller.rb
class MicroPostsController < ApplicationController
  before_action :set_micro_post, only: [:show, :edit, :update, :destroy]

  # GET /micro_posts
  # GET /micro_posts.json
  def index
    @micro_posts = MicroPost.all
  end

  # GET /micro_posts/1
  # GET /micro_posts/1.json
  def show
  end

  # GET /micro_posts/new
  def new
    @micro_post = MicroPost.new
  end

  # GET /micro_posts/1/edit
  def edit
  end

  # POST /micro_posts
  # POST /micro_posts.json
  def create
    @micro_post = MicroPost.new(micro_post_params)

    respond_to do |format|
      if @micro_post.save
        format.html { redirect_to @micro_post, notice: 'Micro post was successfully created.' }
        format.json { render :show, status: :created, location: @micro_post }
      else
        format.html { render :new }
        format.json { render json: @micro_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /micro_posts/1
  # PATCH/PUT /micro_posts/1.json
  def update
    respond_to do |format|
      if @micro_post.update(micro_post_params)
        format.html { redirect_to @micro_post, notice: 'Micro post was successfully updated.' }
        format.json { render :show, status: :ok, location: @micro_post }
      else
        format.html { render :edit }
        format.json { render json: @micro_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /micro_posts/1
  # DELETE /micro_posts/1.json
  def destroy
    @micro_post.destroy
    respond_to do |format|
      format.html { redirect_to micro_posts_url, notice: 'Micro post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micro_post
      @micro_post = MicroPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micro_post_params
      params.require(:micro_post).permit(:content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      login(@user)
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      redirect_to @user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    logout if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      flash[:success] = "Welcome to YAMBA!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "YAMBA"
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end

end

app/helpers/micro_posts_helper.rb
module MicroPostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
  end

  def logout
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    user.remember
    cookies.permanent[:remember_token] = user.remember_token
    cookies.permanent.signed[:user_id] = user.id
  end

  def forget(user)
    user.forget
    cookies.delete(:remember_token)
    cookies.delete(:user_id)
  end

  def current_user
    if(user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif(user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        login user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = {})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size] || 80
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Yet Another Micro Blogging App by Vinu
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "YAMBA", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/micro_posts/_form.html.erb
<%= form_for(@micro_post) do |f| %>
  <% if @micro_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micro_post.errors.count, "error") %> prohibited this micro_post from being saved:</h2>

      <ul>
      <% @micro_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/micro_posts/edit.html.erb
<h1>Editing Micro Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @micro_post %> |
<%= link_to 'Back', micro_posts_path %>

app/views/micro_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Micro Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @micro_posts.each do |micro_post| %>
      <tr>
        <td><%= micro_post.content %></td>
        <td><%= micro_post.user_id %></td>
        <td><%= link_to 'Show', micro_post %></td>
        <td><%= link_to 'Edit', edit_micro_post_path(micro_post) %></td>
        <td><%= link_to 'Destroy', micro_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micro post', new_micro_post_path %>

app/views/micro_posts/new.html.erb
<h1>New Micro Post</h1>

<%= render 'form' %>

<%= link_to 'Back', micro_posts_path %>

app/views/micro_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micro_post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micro_post.user_id %>
</p>

<%= link_to 'Edit', edit_micro_post_path(@micro_post) %> |
<%= link_to 'Back', micro_posts_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Us</h1>
<p>
  We know the world cried out for YAMBA, and here it is!!!
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact Us</h1>
<p>
  Please let us know what you think of awesomatic YAMBA!!
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>Find out here how to take our YAMBA to a spin.</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the YAMBA</h1>

  <h2>
    Are you ready to take <strong>Yet Another Micro Blogging App</strong> to a spin?
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for @user do |f| %>
    <%= render "shared/error_messages" %>

    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>

    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>

    <%= f.submit "Create my account", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for(@user) %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>